// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreatePairingSession() {
  return window['go']['main']['App']['CreatePairingSession']();
}

export function GetConnectedClients() {
  return window['go']['main']['App']['GetConnectedClients']();
}

export function GetDeviceCredentials() {
  return window['go']['main']['App']['GetDeviceCredentials']();
}

export function GetStoredRelayURL() {
  return window['go']['main']['App']['GetStoredRelayURL']();
}

export function PingRelay() {
  return window['go']['main']['App']['PingRelay']();
}

export function StoreRelayURL(arg1) {
  return window['go']['main']['App']['StoreRelayURL'](arg1);
}
