// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {services} from '../models';
import {relay} from '../models';
import {main} from '../models';

export function CheckForUpdates():Promise<services.UpdateResponse>;

export function CreatePairingSession():Promise<relay.PairingSessionResponse>;

export function CreateWorkspace(arg1:string):Promise<main.WorkspacePayload>;

export function DownloadAndInstallUpdate(arg1:string,arg2:string):Promise<void>;

export function GetConnectedClients():Promise<Array<relay.MobileClient>>;

export function GetCurrentVersion():Promise<string>;

export function GetDesktopStatus():Promise<main.DesktopStatusPayload>;

export function GetDeviceCredentials():Promise<relay.DeviceCredentials>;

export function GetFullVersionInfo():Promise<Record<string, string>>;

export function GetServerBaseURL():Promise<string>;

export function GetStoredRelayURL():Promise<string>;

export function GetVersionString():Promise<string>;

export function InstallFromBinaryData(arg1:Array<number>,arg2:string):Promise<void>;

export function ListWorkspaces():Promise<Array<main.WorkspacePayload>>;

export function PingRelay():Promise<boolean>;

export function SelectWorkspaceDirectory():Promise<string>;

export function StoreRelayURL(arg1:string):Promise<void>;
