// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreatePairingSession() {
  return window['go']['main']['App']['CreatePairingSession']();
}

export function CreateWorkspace(arg1) {
  return window['go']['main']['App']['CreateWorkspace'](arg1);
}

export function GetConnectedClients() {
  return window['go']['main']['App']['GetConnectedClients']();
}

export function GetDesktopStatus() {
  return window['go']['main']['App']['GetDesktopStatus']();
}

export function GetDeviceCredentials() {
  return window['go']['main']['App']['GetDeviceCredentials']();
}

export function GetServerBaseURL() {
  return window['go']['main']['App']['GetServerBaseURL']();
}

export function GetStoredRelayURL() {
  return window['go']['main']['App']['GetStoredRelayURL']();
}

export function ListWorkspaces() {
  return window['go']['main']['App']['ListWorkspaces']();
}

export function PingRelay() {
  return window['go']['main']['App']['PingRelay']();
}

export function SelectWorkspaceDirectory() {
  return window['go']['main']['App']['SelectWorkspaceDirectory']();
}

export function StoreRelayURL(arg1) {
  return window['go']['main']['App']['StoreRelayURL'](arg1);
}
