// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {relay} from '../models';
import {main} from '../models';

export function CreatePairingSession():Promise<relay.PairingSessionResponse>;

export function CreateWorkspace(arg1:string):Promise<main.WorkspacePayload>;

export function GetConnectedClients():Promise<Array<relay.MobileClient>>;

export function GetDeviceCredentials():Promise<relay.DeviceCredentials>;

export function GetServerBaseURL():Promise<string>;

export function GetStoredRelayURL():Promise<string>;

export function ListWorkspaces():Promise<Array<main.WorkspacePayload>>;

export function PingRelay():Promise<boolean>;

export function SelectWorkspaceDirectory():Promise<string>;

export function StoreRelayURL(arg1:string):Promise<void>;
