// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {relay} from '../models';

export function CreatePairingSession():Promise<relay.PairingSessionResponse>;

export function GetDeviceCredentials():Promise<relay.DeviceCredentials>;

export function GetStoredRelayURL():Promise<string>;

export function PingRelay():Promise<boolean>;

export function StoreRelayURL(arg1:string):Promise<void>;
