// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlc

import (
	"database/sql"
)

type Workspace struct {
	ID                string         `json:"id"`
	Name              string         `json:"name"`
	Directory         string         `json:"directory"`
	Description       sql.NullString `json:"description"`
	OpencodeProjectID sql.NullString `json:"opencodeProjectId"`
	CodexWorkspaceID  sql.NullString `json:"codexWorkspaceId"`
	ClaudeWorkspaceID sql.NullString `json:"claudeWorkspaceId"`
	CreatedAt         int64          `json:"createdAt"`
	UpdatedAt         int64          `json:"updatedAt"`
}
