// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: workspaces.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createWorkspace = `-- name: CreateWorkspace :one
INSERT INTO workspaces (
    name,
    directory,
    description,
    opencode_project_id,
    codex_workspace_id,
    claude_workspace_id,
    created_at,
    updated_at
) VALUES (
    ?1,
    ?2,
    ?3,
    ?4,
    ?5,
    ?6,
    ?7,
    ?8
)
RETURNING
    id,
    name,
    directory,
    description,
    opencode_project_id,
    codex_workspace_id,
    claude_workspace_id,
    created_at,
    updated_at
`

type CreateWorkspaceParams struct {
	Name              string         `json:"name"`
	Directory         string         `json:"directory"`
	Description       sql.NullString `json:"description"`
	OpencodeProjectID sql.NullString `json:"opencodeProjectId"`
	CodexWorkspaceID  sql.NullString `json:"codexWorkspaceId"`
	ClaudeWorkspaceID sql.NullString `json:"claudeWorkspaceId"`
	CreatedAt         int64          `json:"createdAt"`
	UpdatedAt         int64          `json:"updatedAt"`
}

func (q *Queries) CreateWorkspace(ctx context.Context, arg CreateWorkspaceParams) (Workspace, error) {
	row := q.db.QueryRowContext(ctx, createWorkspace,
		arg.Name,
		arg.Directory,
		arg.Description,
		arg.OpencodeProjectID,
		arg.CodexWorkspaceID,
		arg.ClaudeWorkspaceID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Directory,
		&i.Description,
		&i.OpencodeProjectID,
		&i.CodexWorkspaceID,
		&i.ClaudeWorkspaceID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWorkspaceByDirectory = `-- name: GetWorkspaceByDirectory :one
SELECT
    id,
    name,
    directory,
    description,
    opencode_project_id,
    codex_workspace_id,
    claude_workspace_id,
    created_at,
    updated_at
FROM workspaces
WHERE directory = ?
LIMIT 1
`

func (q *Queries) GetWorkspaceByDirectory(ctx context.Context, directory string) (Workspace, error) {
	row := q.db.QueryRowContext(ctx, getWorkspaceByDirectory, directory)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Directory,
		&i.Description,
		&i.OpencodeProjectID,
		&i.CodexWorkspaceID,
		&i.ClaudeWorkspaceID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWorkspaceByOpencodeProjectID = `-- name: GetWorkspaceByOpencodeProjectID :one
SELECT
    id,
    name,
    directory,
    description,
    opencode_project_id,
    codex_workspace_id,
    claude_workspace_id,
    created_at,
    updated_at
FROM workspaces
WHERE opencode_project_id = ?
LIMIT 1
`

func (q *Queries) GetWorkspaceByOpencodeProjectID(ctx context.Context, opencodeProjectID sql.NullString) (Workspace, error) {
	row := q.db.QueryRowContext(ctx, getWorkspaceByOpencodeProjectID, opencodeProjectID)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Directory,
		&i.Description,
		&i.OpencodeProjectID,
		&i.CodexWorkspaceID,
		&i.ClaudeWorkspaceID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listWorkspaces = `-- name: ListWorkspaces :many
SELECT
    id,
    name,
    directory,
    description,
    opencode_project_id,
    codex_workspace_id,
    claude_workspace_id,
    created_at,
    updated_at
FROM workspaces
ORDER BY name ASC, directory ASC
`

func (q *Queries) ListWorkspaces(ctx context.Context) ([]Workspace, error) {
	rows, err := q.db.QueryContext(ctx, listWorkspaces)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Workspace
	for rows.Next() {
		var i Workspace
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Directory,
			&i.Description,
			&i.OpencodeProjectID,
			&i.CodexWorkspaceID,
			&i.ClaudeWorkspaceID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWorkspace = `-- name: UpdateWorkspace :one
UPDATE workspaces
SET
    name = ?1,
    description = ?2,
    opencode_project_id = ?3,
    codex_workspace_id = ?4,
    claude_workspace_id = ?5,
    updated_at = ?6
WHERE directory = ?7
RETURNING
    id,
    name,
    directory,
    description,
    opencode_project_id,
    codex_workspace_id,
    claude_workspace_id,
    created_at,
    updated_at
`

type UpdateWorkspaceParams struct {
	Name              string         `json:"name"`
	Description       sql.NullString `json:"description"`
	OpencodeProjectID sql.NullString `json:"opencodeProjectId"`
	CodexWorkspaceID  sql.NullString `json:"codexWorkspaceId"`
	ClaudeWorkspaceID sql.NullString `json:"claudeWorkspaceId"`
	UpdatedAt         int64          `json:"updatedAt"`
	Directory         string         `json:"directory"`
}

func (q *Queries) UpdateWorkspace(ctx context.Context, arg UpdateWorkspaceParams) (Workspace, error) {
	row := q.db.QueryRowContext(ctx, updateWorkspace,
		arg.Name,
		arg.Description,
		arg.OpencodeProjectID,
		arg.CodexWorkspaceID,
		arg.ClaudeWorkspaceID,
		arg.UpdatedAt,
		arg.Directory,
	)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Directory,
		&i.Description,
		&i.OpencodeProjectID,
		&i.CodexWorkspaceID,
		&i.ClaudeWorkspaceID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertWorkspaceFromSync = `-- name: UpsertWorkspaceFromSync :one
INSERT INTO workspaces (
    name,
    directory,
    description,
    opencode_project_id,
    created_at,
    updated_at
) VALUES (
    ?1,
    ?2,
    ?3,
    ?4,
    ?5,
    ?6
)
ON CONFLICT(directory) DO UPDATE SET
    name = excluded.name,
    description = COALESCE(excluded.description, workspaces.description),
    opencode_project_id = COALESCE(excluded.opencode_project_id, workspaces.opencode_project_id),
    updated_at = excluded.updated_at
RETURNING
    id,
    name,
    directory,
    description,
    opencode_project_id,
    codex_workspace_id,
    claude_workspace_id,
    created_at,
    updated_at
`

type UpsertWorkspaceFromSyncParams struct {
	Name              string         `json:"name"`
	Directory         string         `json:"directory"`
	Description       sql.NullString `json:"description"`
	OpencodeProjectID sql.NullString `json:"opencodeProjectId"`
	CreatedAt         int64          `json:"createdAt"`
	UpdatedAt         int64          `json:"updatedAt"`
}

func (q *Queries) UpsertWorkspaceFromSync(ctx context.Context, arg UpsertWorkspaceFromSyncParams) (Workspace, error) {
	row := q.db.QueryRowContext(ctx, upsertWorkspaceFromSync,
		arg.Name,
		arg.Directory,
		arg.Description,
		arg.OpencodeProjectID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Directory,
		&i.Description,
		&i.OpencodeProjectID,
		&i.CodexWorkspaceID,
		&i.ClaudeWorkspaceID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
